// Builds web/vendor/gameicons/icons.css from game-icons.net (CC BY 3.0).
//
// Icons are shipped as CSS masks rather than a font: a mask inherits the
// element's colour through `background-color: currentColor`, so every icon
// still takes the per-action --c tint, and only the icons we actually use get
// downloaded. Sized in em, so the existing font-size rules keep working.
//
//   node tools/build-icons.mjs
//
// Add a name to ICONS in web/app.js, list it here, re-run, commit the result.
import { mkdirSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "web", "vendor", "gameicons");

// every game-icons name the app references (see ICONS in web/app.js)
const NAMES = [
  "all-seeing-eye", "anticlockwise-rotation", "arcing-bolt", "binoculars", "bolt-spell-cast",
  "book-pile", "cancel", "card-burn", "card-discard", "card-draw", "card-exchange", "card-pickup",
  "card-random", "castle", "chat-bubble", "check-mark", "checklist", "chess-king",
  "circle", "clockwise-rotation", "crossed-swords", "crown", "dragon-head", "empty-chessboard",
  "fast-forward-button", "gears", "gemini", "gems", "hidden", "hood", "hourglass", "invisible",
  "magic-swirl", "magnifying-glass", "moon", "mountains", "pencil", "plain-arrow", "plain-circle",
  "play-button", "player-next", "recycle", "return-arrow", "scroll-unfurled", "shaking-hands",
  "shield", "shield-disabled", "snatch", "sparkles", "spectacles", "stack", "sword-break",
  "sword-clash", "token", "trash-can", "up-card",
];

const svgFor = async (name) => {
  const r = await fetch(`https://api.iconify.design/game-icons/${name}.svg`);
  if (!r.ok) throw new Error(`${name}: HTTP ${r.status}`);
  const svg = (await r.text()).trim();
  if (!svg.startsWith("<svg")) throw new Error(`${name}: not an svg`);
  return svg;
};

const rules = [];
for (const name of NAMES) {
  const svg = await svgFor(name);
  // keep the URI readable where it is safe to: only the characters that would
  // break a css url() are escaped
  const uri = svg.replace(/"/g, "'").replace(/[<>#%{}\n]/g, (c) => encodeURIComponent(c));
  rules.push(`.gi-${name}{--gi:url("data:image/svg+xml,${uri}")}`);
}

const css = `/* game-icons.net — Lorc, Delapouite and contributors, CC BY 3.0.
   Generated by tools/build-icons.mjs; do not edit by hand. */
.gi {
  display: inline-block; width: 1em; height: 1em; flex: none; vertical-align: -0.125em;
  background-color: currentColor;
  -webkit-mask: var(--gi) center / contain no-repeat;
  mask: var(--gi) center / contain no-repeat;
}
.gi-rot180 { transform: rotate(180deg); }
${rules.join("\n")}
`;

mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, "icons.css"), css);
console.log(`${NAMES.length} icons -> ${join(OUT, "icons.css")} (${(css.length / 1024).toFixed(0)} KB)`);
